name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: yarn install and build
        run: |
          yarn install
          yarn build
      - uses: actions/upload-artifact@v1
      - name: Archive production artifacts
        with:
          name: build
          path: build
